import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-inmuebles',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './inmuebles.component.html',
  styleUrl: './inmuebles.component.css'
})
export class InmueblesComponent {
  inmuebles = [
    {id: '1', nombre: 'Inmueble Nº 1', detalles: 'Es conocida la predilección que las realezas de diversos lugares del Golfo Pérsico tienen por pasar el período estival en Marbella, ciudad que alberga numerosos palacios de estas dinastías, como la Saudí o la de Emiratos Árabes, y que han elegido este verano la Costa del Sol para descansar. Un histórico desembarco de grandes fortunas de Oriente que ha vuelto a agitar con fuerza el mercado inmobiliario marbellí.La directora de la inmobiliaria Kristina Szekely, con el mismo nombre, lo confirma. Szekely apunta que este verano ha alquilado inmuebles a miembros de las realezas saudí y emiratí incidiendo en que eligen casas "en primera línea de playa, con seis u ocho dormitorios y vistas al mar", a partir de 25.000 euros el mes.'},
    {id: '2', nombre: 'Inmueble Nº2', detalles: 'El concepto interior de la casa está muy cuidado. Es una villa diseñada al detalle, creando un ambiente hogareño pero con detalles que marcan la elegancia y el carácter de la propiedad. El estilo interior es de estilo contemporáneo, combinando el mármol con grandes ventanales y elegantes suelos de madera. Además, cuenta con un exterior de estilo mediterráneo. Esto hace que la casa se integre perfectamente en el entorno.La vivienda se ha diseñado al detalle con todo tipo de facilidades. Consta de tres plantas. En la principal, hay un gran hall de entrada, dos dormitorios con armarios empotrados y baño en suite y un aseo de cortesía. Además de un amplio salón comunicado con la zona de comedor y cocina independiente (equipada con electrodomésticos Gaggenau). Todas las estancias tienen salida directa al exterior por grandes ventanales que dan a una amplio porche en el jadrín.En la planta superior, está el dormitorio principal y otros dos dormitorios ( de gran tamaño). Todos ellos con zona de vestidor, baño completo y amplias terrazas con vistas panorámicas a la costa.En la planta baja, la vivienda alberga una zona de gimnasio con pequeña piscina y sauna. Además de una sala diáfana con múltiples usos y zona de garaje (con capacidad para 3 coches en el interior y 2 en el exterior).'},
    {id:'3', nombre: 'Inmueble Nº3', detalles: 'La vivienda se ha diseñado al detalle con todo tipo de facilidades. Consta de tres plantas. En la principal, hay un gran hall de entrada, dos dormitorios con armarios empotrados y baño en suite y un aseo de cortesía. Además de un amplio salón comunicado con la zona de comedor y cocina independiente (equipada con electrodomésticos Gaggenau). Todas las estancias tienen salida directa al exterior por grandes ventanales que dan a una amplio porche en el jadrín. En la planta superior, está el dormitorio principal y otros dos dormitorios ( de gran tamaño). Todos ellos con zona de vestidor, baño completo y amplias terrazas con vistas panorámicas a la costa.En la planta baja, la vivienda alberga una zona de gimnasio con pequeña piscina y sauna. Además de una sala diáfana con múltiples usos y zona de garaje (con capacidad para 3 coches en el interior y 2 en el exterior).La parcela se encuentra ajardinada con una zona de piscina. Consta con una entrada principal desde la calle y la de acceso al garaje es por un pequeño paso privado de varias viviendas.Todas las estancias tienen A/C y calefacción por suelo radiante. Los muebles y decoración de la casa pueden incluirse en la venta (con coste adicional)'},
    {id:'4', nombre: 'Inmueble Nº4', detalles: 'Villa familiar completamente reformada con impresionantes vistas al mar en el corazón del Valle del Golf (Nueva Andalucía). La propiedad se distribuye en 3 niveles y ofrece un diseño de espacio abierto con mucha luz natural. El nivel de entrada incluye sala de estar/cocina abierta, 3 dormitorios dobles, 2 baños y un aseo de invitados. La planta superior ofrece 2 dormitorios: suite principal y un dormitorio de invitados y un baño. La terraza solarium de 90m2 disfruta de hermosas vistas de la montaña de la Concha en el este, sobre el campo de golf y Puerto Banús hacia el sur y el sol de la tarde en el lado oeste. La propiedad dispone de numerosos espacios de ocio: sótano con sala de TV, gimnasio, sauna y zona de juegos, además de instalaciones exteriores: piscina de agua salada con acceso desde el salón comedor, zona de barbacoa y comedor exterior, varias zonas chill-out . Propiedad ideal para vivir en familia o como casa de vacaciones para los amantes del golf.'},
    {id:'5', nombre: 'Inmueble Nº5', detalles: 'Tan estético como funcional. La sala de estar cuenta con un diseño de planta abierta, y la cómoda sala de estar ofrece vistas directas al exterior. Los muebles y accesorios ejemplifican la atención al detalle en el diseño. Al lado se encuentra el comedor, que también ofrece increíbles vistas a la terraza y al aire libre. La cocina a medida está elegantemente diseñada con carpintería de madera y una maravillosa isla de mármol, además de ofrecer lo último en tecnología.Electrodomésticos de cocina Gaggenau. La isla de la cocina tiene una mesa de comedor más pequeña conectada para mayor versatilidad. La terraza del nivel superior rodea las habitaciones, con una encantadora zona chill-out ideal para contemplar el atardecer o relajarse. El nivel superior, que se distribuye en 3 niveles, está reservado para los dormitorios y el ilustre dormitorio principal. Todas las habitaciones han sido diseñadas para maximizar la comodidad y mantener el estilo en diseño. El dormitorio principal se beneficia de vistas panorámicas y terraza. El baño principal es una ventaja adicional al espacio con una impresionante bañera independiente y detalles en mármol. Villa Alfma tiene todo lo que necesita, con el nivel inferior de la propiedad reservado para las increíbles comodidades que incluyen una asombrosa sala de entretenimiento con una mesa de billar hecha a medida, bodega de vinos, cine y bar personalizado. También hay un gimnasio en casa y una preciosa sauna. Una sala de televisión también se encuentra en este nivel para mayor entretenimiento. La calefacción por suelo radiante recorre toda la propiedad para brindar una capa adicional de comodidad y lujo. Villa Alfma tiene todo lo que uno pueda necesitar: increíbles comodidades, asombrosas terrazas al aire libre, impecable diseño interior, amplias vistas panorámicas y una ubicación privilegiada en Nueva Andalucía. Villa Alfma es verdaderamente la mejor oferta inmobiliaria dentro de su categoría en Marbella.'}
  ];
}
